# Want to disable a check for a specific case? To disable checks inline:
# http://docs.rubocop.org/en/latest/configuration/#disabling-cops-within-source-code

require:
  - standard

plugins:
  - standard-custom
  - standard-performance
  - rubocop-performance

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml

# Add our excludes on top of RuboCop's defaults, otherwise CI descends into vendored gems.
inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - "test/dummy/db/schema.rb"
